### ISSUE TITLE
ncml template for testing

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/yaml2ncml#5]
@rsignell-usgs I need the "working" `ncml` file.

**Comment by rsignell-usgs** [comment]
If you need that, don't you need some same sample netcdf filed and yaml file as well?

**Comment by ocefpaf** [comment]
I have the yaml (from your script) and I do no need a NetCDF file (for
now). Just an expected ncml to compare is fine.
Em 29/05/2015 3:32 PM, "Rich Signell" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
We have the file [roms.yaml](https://github.com/ocefpaf/yaml2ncml/blob/master/yaml2ncml/tests/roms.yaml), so I am closing this.
